name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # 단일 작업으로 통합
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install pnpm
      run: npm install -g pnpm@9

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build application
      run: pnpm build --filter=game-notification-assistant

    - name: Install Playwright browsers
      run: pnpm --filter=e2e exec playwright install --with-deps

    - name: Run E2E tests
      run: pnpm --filter=e2e test
      env:
        CI: true
        HEADLESS: true
        SHOW_STEP_LOG: false

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          apps/e2e/test-results/
          apps/e2e/playwright-report/
        retention-days: 7
